### ISSUE TITLE
checklist prod

### ISSUE THREAD

**Issue by nicolasdb** [openfab-lab/chic2.0#14]
- [ ] wood MP 12mm
  - [x] cut
  - [x] sand
  - [x] drill
  - [x] assemble
- [ ] print 3D
  - [x] 1x 01Universal_Dovetail Table_Clamp_40mm.stl
  - [x] 1x 01Universal_Dovetail_Set_Screw_40mm.stl
  - [x] 1x 01FixPoint.stl
  - [x] 1x FlexHolder.stl
  - [x] 1x proxxon-FlexMountAB.stl
  - [x] 1x Shield.stl
  - [x] 2x UltraBolt.stl
  - [x] 1x 03EndPoint.stl

**Comment by nicolasdb** [comment]
To cut and prepare wood. 
For 3 pantolino, 30min to cut, 1h30 to drill, to sand and to assemble. 
2h total.

![image](https://user-images.githubusercontent.com/12049360/33239911-eaa1edf4-d2ac-11e7-9657-ad5ff2c0346a.png)

![image](https://user-images.githubusercontent.com/12049360/33239913-f6bacb10-d2ac-11e7-832b-a8f8cece225c.png)

![image](https://user-images.githubusercontent.com/12049360/33239914-fb10ccf0-d2ac-11e7-86c6-93dc89221760.png)

![image](https://user-images.githubusercontent.com/12049360/33239915-00ed9dba-d2ad-11e7-8ee4-be4c3d352de4.png)

![image](https://user-images.githubusercontent.com/12049360/33239916-063d6aa2-d2ad-11e7-9e27-056262db71cb.png)

![image](https://user-images.githubusercontent.com/12049360/33239919-0d616e14-d2ad-11e7-939f-ebca51acec5f.png)

![image](https://user-images.githubusercontent.com/12049360/33239920-11668166-d2ad-11e7-8089-204a35a761cb.png)

![image](https://user-images.githubusercontent.com/12049360/33239924-2599d124-d2ad-11e7-909a-c7aa21d9f8bf.png)
